version: '3.7'

services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - 8080
    depends_on:
      - db
    env_file:
      - ./.env-docker
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: