version: '3.7'

services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  web:
    restart: always
    build: .
    command: /root/.poetry/bin/poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data: