version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/restaurant-api
    docker:
      - image: circleci/python:3.6.8
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: restaurant_api
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}
      - run:
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      # Last step, runs our tests ommiting the dependencies path (so we don't take their coverage into account)
      # And send our coverage somewhere, in this case, coveralls
      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run application.py tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
